// TOOL:     vlog2tf
// DATE:     Wed Apr 03 14:32:06 2013
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   DeBounce
// DESIGN:   DeBounce
// FILENAME: DeBounce_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond


`timescale 1 ns / 100 ps

module DeBounce_tb();

    // Inputs
    reg clk;
    reg n_reset;
    reg button_in;

    // Outputs
    wire DB_out;

    // Instantiate the UUT
    DeBounce UUT (
        .clk(clk),
        .n_reset(n_reset),
        .button_in(button_in),
        .DB_out(DB_out)
    );

    // Initialize Inputs
    initial begin
        $display ($time, " << Starting the Simulation >> ");
        clk = 1'b0;
        n_reset = 1'b0;
        button_in = 1'b0;
        #200 n_reset = 1'b1;      // at time 200 release the reset
    end

    // clock
    always #10 clk = ~clk;    // every ten nanoseconds invert the clock

    // stimulus (pattern) -- keep as originally generated
    initial begin
        // start with stable 0
        button_in = 1'b0;
        #40000 button_in = 1'b1;
        #400 button_in = 1'b0;
        #800 button_in = 1'b1;
        #800 button_in = 1'b0;
        #800 button_in = 1'b1;
        #40000 button_in = 1'b0;
        #4000 button_in = 1'b1;
        #40000 button_in = 1'b0;
        #400 button_in = 1'b1;
        #800 button_in = 1'b0;
        #800 button_in = 1'b1;
        #800 button_in = 1'b0;
        #40000 button_in = 1'b1;
        #4000 button_in = 1'b0;
    end

    // waveform + monitor for debugging
    initial begin
        $dumpfile("DeBounce_tb.vcd");
        $dumpvars(0, DeBounce_tb);
        $display("time\tclk\tn_reset\tbutton_in\tDB_out");
        $monitor("%0t\t%b\t%b\t%b\t%b", $time, clk, n_reset, button_in, DB_out);
    end

    // timeout to finish simulation in case nothing else calls $finish
    initial begin
        #1000000; // ajusta tiempo total de simulación si necesitas más/menos
        $display("Timeout reached at %0t - finishing simulation", $time);
        $finish;
    end

endmodule